apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.rules: |-
    groups:
    - name: alert
      rules:
      - alert: High Count
        expr: sum(hello_processed_total) > 10
        for: 1m
        annotations:
          summary: High Count Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    scrape_configs:
      - job_name: 'go-prometheus-monitoring'

        static_configs:
        - targets:
          - hello-world:8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
  
        - name: prometheus-storage-volume
          emptyDir: {}
--- 

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
    dev.okteto.com/auto-ingress: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port:   "9090"
spec:
  type: ClusterIP  
  ports:
  - name: "prometheus"
    port: 9090
  selector:
    app: prometheus
